### ISSUE TITLE
Not compatible with Visual studio 2022

### ISSUE THREAD

**Issue by its-mash** [Tajko725/AAASnippet#2]
## Error
![image](https://user-images.githubusercontent.com/13703633/190318882-79a38b7a-f503-4da5-8710-9e9b4d7d6c4e.png)
## Log
![image](https://user-images.githubusercontent.com/13703633/190318770-54a2f258-2008-438b-b07e-fe713dbb28e7.png)

**Comment by Tajko725** [comment]
I checked on the Internet and tried to solve it, unfortunately I can not reproduce this error, because on my other computer with Visual Studio 2022 Prof installs correctly. One workaround to solve this problem is to install Visual Studio extension 'Visual Studio extensions development'. I just happened to have the version for CoreEditor set to 17.0,18.0, so it should work normally for you. In other cases of extensions and with the same error, reinstalling the extension helps, so you can check that too, check [here](https://codeutility.org/missing-microsoft-visualstudio-component-coreeditor-when-installing-visual-studio-extension-stack-overflow/)

![image](https://user-images.githubusercontent.com/66118924/190490387-de29ddd3-2547-49aa-8c16-7a783afe85a1.png)
